version: '3.8'
services:
  orchestrator:
    build:
      context: .
      args:
        digitalocean_access_token: ${DIGITALOCEAN_ACCESS_TOKEN}
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
