version: '3.8'
services:
  orchestrator:
    build:
      context: .
      args:
        digitalocean_access_token: ${DIGITALOCEAN_ACCESS_TOKEN}
    command: sh -c "/wait && /orchestrator 1-10000000000"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - POSTGRES_CONN=postgresql://postgres?sslmode=disable&user=postgres&password=postgres
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
