parameters: {}
environment:
  WASABI_KEY: ${WASABI_KEY}
  WASABI_SECRET: ${WASABI_SECRET}
  WASABI_BUCKET: ${WASABI_BUCKET}
  WASABI_REGION: ${WASABI_REGION}
  LOG_LEVEL: info
packages:
  - name: scraper
    environment: {}
    parameters: {}
    actions:
      - name: sync
        limits:
          memory: 1024
          timeout: 30000
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

