parameters: {}
environment:
  WASABI_ACCESS_KEY: ${WASABI_ACCESS_KEY}
  WASABI_SECRET_KEY: ${WASABI_SECRET_KEY}
  WASABI_BUCKET: ${WASABI_BUCKET}
  WASABI_REGION: ${WASABI_REGION}
  LOG_LEVEL: trace
packages:
  - name: scraper
    environment: {}
    parameters: {}
    actions:
      - name: sync
        limits:
          memory: 1024
          timeout: 30000
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

