parameters: {}
environment:
  WASABI_ACCESS_KEY: ${WASABI_ACCESS_KEY}
  WASABI_SECRET_KEY: ${WASABI_SECRET_KEY}
  WASABI_BUCKET: ${WASABI_BUCKET}
  WASABI_REGION: ${WASABI_REGION}
  INDEXER_PROXY: ${INDEXER_PROXY}
  LOG_LEVEL: debug
packages:
  - name: scraper
    environment: {}
    parameters: {}
    actions:
      - name: sync
        limits:
          memory: 1024
          timeout: 30000
        runtime: 'go:default'

