parameters: {}
environment:
  SPACES_KEY: ${SPACES_KEY}
  SPACES_SECRET: ${SPACES_SECRET}
  SPACES_BUCKET: ${SPACES_BUCKET}
  SPACES_REGION: ${SPACES_REGION}
packages:
  - name: scraper
    environment: {}
    parameters: {}
    actions:
      - name: sync
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

