# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WASABI_KEY: ${{ secrets.WASABI_KEY }}
  WASABI_SECRET: ${{ secrets.WASABI_SECRET }}
  WASABI_BUCKET: suremarc-rblx-assets
  WASABI_REGION: us-east-1
  LOG_LEVEL: trace

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        
      - name: Vet
        run: |
          go vet ./... 
          cd packages/scraper/sync
          go vet ./...
      
      - name: Test
        run: |
          go test -v ./...
          cd packages/scraper/sync
          go test -v ./...
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install serverless
        run: doctl serverless install
      
      - name: Connect to functions
        run: doctl serverless connect

      - name: Deploy
        run: doctl serverless deploy . --remote-build
      
      - name: Test
        run: |
          cd packages/scraper/sync/client
          go test -tags=service_test -v .
