# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SPACES_KEY: ${{ secrets.SPACES_KEY }}
  SPACES_SECRET: ${{ secrets.SPACES_SECRET }}
  SPACES_BUCKET: assets-test
  SPACES_REGION: nyc3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        
      - name: Build
        run: go build -v ./...
      
      - name: Test
        run: go test -v ./...
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install serverless
        run: doctl serverless install
      
      - name: Connect to functions
        run: doctl serverless connect

      - name: Deploy
        run: doctl serverless deploy . --remote-build
